### ISSUE TITLE
is there protection agains gcode

### ISSUE THREAD

**Issue by jorgeelmundoso** [stouset/secrets#72]
Hello, 

i tried the code and it looks like it does not protect against reading the process memory with gcore from gdb.

code:
```
use std::fs::File;
use std::io::Read;

use std::io::Error;

use std::time::Duration;
use std::thread::sleep;


use secrets::SecretBox;

const KEY_LEN : usize = 10;

fn main() -> Result<(), Error> {

    let mut key = SecretBox::<[u8; KEY_LEN]>::zero();
    File::open("key.txt")?
        .read_exact(key.borrow_mut().as_mut())?;

    let mut cnt = 0u32;

    loop {
        cnt += 1;

        sleep(Duration::from_secs(60));
        if cnt == 10 {
            break;
        }
    }
    Ok(())
}
```

I f you use
```
# gcore -a -o rust_secret_process_dump  $PID
```
you will find the content of key.txt with the strings tool in the generated 
process memory dump.

```
# strings rust_secret_process_dump.$PID | grep (cat key.txt)
``` 

Maybe i missed that this class of attack is not what the library intends to protect from, but could someone elaborate on that.

**Comment by jorgeelmundoso** [comment]
here is the sourceode to gcode from gdb
https://github.com/bminor/binutils-gdb/blob/master/gdb/gcore.c

**Comment by stouset** [comment]
Was this built in `--release` mode? [We call `setrlimit`](https://github.com/stouset/secrets/blob/master/src/ffi/sodium.rs#L73) to set the hard limit for `RLIMIT_CORE` to `0` in non-debug builds.

**Comment by stouset** [comment]
It looks like `gcore` ignores `setrlimit`. I'm not sure there's anything this (or any) library *can* do about a user that has `root` and can probe memory directly.

**Comment by jorgeelmundoso** [comment]
> Was this built in `--release` mode? [We call `setrlimit`](https://github.com/stouset/secrets/blob/master/src/ffi/sodium.rs#L73) to set the hard limit for `RLIMIT_CORE` to `0` in non-debug builds.

Yes it was build with --release.
I was looking for a way to protect secrets inside docker containers, guess that is a really hard one.

**Comment by stouset** [comment]
FWIW, `libsodium` recently added an [`mshield`](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/sodium/utils.c#L738) function that performs in-memory encryption. When that is stabilized and released, I'll be able to use it.

Of course, anyone with similar privileges can still find the key and IV in memory and decrypt the secret, but it does increase the level of effort for such an attach.

**Comment by stouset** [comment]
But yeah, fundamentally there's not much that can be done to protect against a user with `root` who can read arbitrary memory. Page-level protections like `mprotect` only affect the *process'* address space.

The main intent here is to protect against in-process bugs like those that resulted in heartbleed.

Closing since there's not much that can be done here, but when `libsodium` does release a version with `mshield`, I will use it for secrets allocated on the heap.

**Comment by jorgeelmundoso** [comment]
thanks
