### ISSUE TITLE
Any plans to add protection against Specte?

### ISSUE THREAD

**Issue by oblique** [stouset/secrets#73]
One way is what OpenSSH does, which is encrypting sensitive information with a random prekey of 16kb size. Because of the size, attacker is unlikely to retrieve prekey with the current attacks.

OpenSSH commit: https://github.com/openbsd/src/commit/707316f931b35ef67f1390b2a00386bdd0863568

**Comment by stouset** [comment]
Yep. [`sodium_mshield`](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/include/sodium/utils.h#L162) was added to libsodium in a [recent commit](https://github.com/jedisct1/libsodium/commit/bfeca0eb73c1650fa17a3b0f5e845e95f28516a4) but has yet to be released. When it is, I'll incorporate it.

**Comment by U007D** [comment]
Hi, I'm wondering if there are any updates on this?

Thank for all your hard work.

**Comment by stouset** [comment]
I’m out of the country on vacation at the moment but I’ll look and see if this was added to a libsodium release and incorporate it if so.

**Comment by stouset** [comment]
`sodium_mshield` was removed from upstream. https://github.com/jedisct1/libsodium/commit/67a9e796550dda21767dd8888bc25e2bcfaba546
