### ISSUE TITLE
Question about linkage

### ISSUE THREAD

**Issue by oblique** [stouset/secrets#82]
Is there any reason that you explicitly search with `pkg-config` for `libsodium`? 
This is done by `libsodium-sys` with `use-pkg-config` feature flag.

I believe this should be left to the user of the crate. Is it ok with you if I remove the `link` in `build.rs` and add `use-pkg-config` feature flag that enables `libsodium-sys/use-pkg-config`?

**Comment by stouset** [comment]
Is there any reason not to use pkg-config? What's the preferred alternative?
